databases:
  - name: blog_sayfasi_db
    databaseName: blog_sayfasi_db
    user: blog_sayfasi_user

services:
  - type: web
    name: blog_sayfasi
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_sayfasi.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_sayfasi_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: RENDER
        value: true 