services:
  - type: web
    name: blog-sayfasi
    env: python
    buildCommand: "pip install -r requirements.txt && python simple_test.py && python manage.py collectstatic --no-input"
    startCommand: "python manage.py runserver 0.0.0.0:$PORT"
          envVars:
        - key: DEBUG
          value: true
        - key: SECRET_KEY
          generateValue: true
        - key: RENDER
          value: true 