services:
  - type: web
    name: blog-sayfasi
    env: python
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_sayfasi.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: DJANGO_SUPERUSER_USERNAME
        value: ramazancan
      - key: DJANGO_SUPERUSER_EMAIL
        value: ramazan61135@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: 12345678Ramazan
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: RENDER_EXTERNAL_HOSTNAME
        value: blog-sayfasi.onrender.com
      # Cloudinary Settings - Bu değerleri Cloudinary dashboard'dan alın
      - key: CLOUDINARY_CLOUD_NAME
        value: ""  # Cloudinary dashboard'dan alınacak
      - key: CLOUDINARY_API_KEY
        value: ""  # Cloudinary dashboard'dan alınacak
      - key: CLOUDINARY_API_SECRET
        value: ""  # Cloudinary dashboard'dan alınacak

databases:
  - name: blog-sayfasi-db
    databaseName: blog_sayfasi_prod
    user: blog_user 