services:
  - type: web
    name: blog-sayfasi
    env: python
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_sayfasi.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 60 --max-requests 1000 --max-requests-jitter 100"
    envVars:
      - key: DEBUG
        value: "false"  # Production'da false
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: DJANGO_SUPERUSER_USERNAME
        value: ramazancan
      - key: DJANGO_SUPERUSER_EMAIL
        value: ramazan61135@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: 12345678Ramazan
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: RENDER_EXTERNAL_HOSTNAME
        value: blog-sayfasi.onrender.com
      - key: WEB_CONCURRENCY
        value: "1"  # Tek worker kullan (memory için)

databases:
  - name: blog-sayfasi-db
    databaseName: blog_sayfasi_prod
    user: blog_user 