# Generated by Django 5.0.2 on 2025-07-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiziFilm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isim",
                    models.CharField(max_length=200, verbose_name="Dizi/Film İsmi"),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[("dizi", "Dizi"), ("film", "Film")],
                        max_length=10,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "tur",
                    models.CharField(
                        choices=[
                            ("aksiyon", "Aksiyon"),
                            ("komedi", "Komedi"),
                            ("drama", "Drama"),
                            ("korku", "Korku"),
                            ("romantik", "Romantik"),
                            ("bilim_kurgu", "Bilim Kurgu"),
                            ("gerilim", "Gerilim"),
                            ("belgesel", "Belgesel"),
                            ("animasyon", "Animasyon"),
                            ("macera", "Macera"),
                        ],
                        max_length=20,
                        verbose_name="Tür",
                    ),
                ),
                (
                    "fotograf",
                    models.ImageField(upload_to="dizi_film/", verbose_name="Fotoğraf"),
                ),
                ("tanim", models.TextField(verbose_name="Açıklama/Tanım")),
                ("admin_yorumu", models.TextField(verbose_name="Admin Yorumu")),
                ("yayın_yili", models.IntegerField(verbose_name="Yayın Yılı")),
                (
                    "imdb_puani",
                    models.FloatField(blank=True, null=True, verbose_name="IMDB Puanı"),
                ),
                (
                    "sure",
                    models.CharField(
                        help_text="Örn: 120 dk veya 8 sezon",
                        max_length=50,
                        verbose_name="Süre",
                    ),
                ),
                (
                    "onerilen",
                    models.BooleanField(default=True, verbose_name="Önerilen"),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dizi/Film",
                "verbose_name_plural": "Dizi/Filmler",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
    ]
