# Generated by Django 5.0.2 on 2025-07-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anasayfa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeziBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "yer_adi",
                    models.CharField(max_length=200, verbose_name="Gezilen Yer Adı"),
                ),
                ("sehir", models.CharField(max_length=100, verbose_name="Şehir")),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("dogal", "Doğal Güzellik"),
                            ("tarihi", "Tarihi Yer"),
                            ("sehir", "Şehir Turu"),
                            ("sahil", "Sahil/Deniz"),
                            ("dag", "Dağ/Yayla"),
                            ("kultur", "Kültürel"),
                            ("macera", "Macera"),
                            ("yeme_icme", "Yeme İçme"),
                        ],
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "fotograf",
                    models.ImageField(upload_to="gezi_blog/", verbose_name="Fotoğraf"),
                ),
                (
                    "kisa_aciklama",
                    models.TextField(
                        help_text="Kısa tanıtım metni",
                        max_length=300,
                        verbose_name="Kısa Açıklama",
                    ),
                ),
                (
                    "deneyim",
                    models.TextField(
                        help_text="Detaylı gezi deneyiminizi paylaşın",
                        verbose_name="Gezi Deneyimi",
                    ),
                ),
                (
                    "puanim",
                    models.IntegerField(
                        choices=[
                            (1, "⭐ Çok Kötü"),
                            (2, "⭐⭐ Kötü"),
                            (3, "⭐⭐⭐ Orta"),
                            (4, "⭐⭐⭐⭐ İyi"),
                            (5, "⭐⭐⭐⭐⭐ Mükemmel"),
                        ],
                        verbose_name="Puanım",
                    ),
                ),
                ("ziyaret_tarihi", models.DateField(verbose_name="Ziyaret Tarihi")),
                (
                    "en_iyi_mevsim",
                    models.CharField(
                        choices=[
                            ("ilkbahar", "İlkbahar"),
                            ("yaz", "Yaz"),
                            ("sonbahar", "Sonbahar"),
                            ("kis", "Kış"),
                            ("yil_boyu", "Yıl Boyu"),
                        ],
                        max_length=15,
                        verbose_name="En İyi Mevsim",
                    ),
                ),
                (
                    "maliyet",
                    models.CharField(
                        help_text="Örn: 500-1000 TL",
                        max_length=100,
                        verbose_name="Yaklaşık Maliyet",
                    ),
                ),
                (
                    "konaklama",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Konaklama Önerisi"
                    ),
                ),
                ("ulasim", models.TextField(verbose_name="Ulaşım Bilgileri")),
                (
                    "tavsiyeler",
                    models.TextField(
                        help_text="Gideceklere önerileriniz",
                        verbose_name="Tavsiyelerim",
                    ),
                ),
                (
                    "onerilen",
                    models.BooleanField(default=True, verbose_name="Önerilen"),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gezi Blog",
                "verbose_name_plural": "Gezi Blogları",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
    ]
